name: Fetch AOE2 Personal Stats

on:
  workflow_dispatch:

jobs:
  fetch-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch AOE2 Personal Stats
      run: |
        set -e
        echo "Fetching data for profile: /steam/76561198067966567"
        ENCODED_PROFILE=%2Fsteam%2F76561198067966567
        URL="https://aoe-api.reliclink.com/community/leaderboard/GetPersonalStat?title=age2&profile_names=%5B%22${ENCODED_PROFILE}%22%5D"
        echo "Encoded profile: ${ENCODED_PROFILE}"
        curl -sS "${URL}" -o aoe2_personal_stats.json
        cat aoe2_personal_stats.json

    - name: Upload JSON output
      uses: actions/upload-artifact@v2
      with:
        name: aoe2_personal_stats
        path: aoe2_personal_stats.json
