name: Check JSON Contents

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch JSON and Print
        run: |
          set -x
          url='https://aoe-api.reliclink.com/community/leaderboard/GetPersonalStat?title=age2&profile_names=%5B%22/steam/76561198067966567%22%5D'
          response=$(curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "$url")
          echo "Response: $response"
        shell: /bin/bash
