name: Update ELO Data

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5mins
  push:
    branches:
      - main

jobs:
  update-elo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch ELO Data and Update JSON
        run: |
          set -e
          echo "[]" > elo_data.json
          steamIDs=(/steam/76561198403361404 /steam/76561198040642066 /steam/76561198151727332 /steam/76561198067966567)
          for steamID in "${steamIDs[@]}"; do
            response=$(curl -s "https://aoe-api.reliclink.com/community/leaderboard/GetPersonalStat?title=age2&profile_names=\[%22$steamID%22\]")
            elo1v1=$(echo "$response" | jq '.leaderboardStats[] | select(.leaderboard_id == 3) | .rating')
            eloTeam=$(echo "$response" | jq '.leaderboardStats[] | select(.leaderboard_id == 4) | .rating')
            [ -z "$elo1v1" ] && elo1v1=null
            [ -z "$eloTeam" ] && eloTeam=null
            jq --arg steamID "$steamID" --argjson elo1v1 "$elo1v1" --argjson eloTeam "$eloTeam" \
            '. += [{
              "steamID": $steamID,
              "elo1v1": $elo1v1,
              "eloTeam": $eloTeam
                }]' elo_data.json > tmp.json && mv tmp.json elo_data.json
          done

      - name: Commit and Push JSON
        env:
          CLASSIC_PAT: ${{ secrets.CLASSIC_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.CLASSIC_PAT }}@github.com/${{ github.repository }}
          git add elo_data.json
          git commit -m "Update ELO data"
          git push origin HEAD:main
