name: Check JSON Contents

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch JSON and Print
        run: |
          response=$(curl -s 'https://aoe-api.reliclink.com/community/leaderboard/GetPersonalStat?title=age2&profile_names=[%22/steam/76561198067966567%22]')
          echo "Response: $response"
          # Check if the response is valid JSON
          if echo "$response" | jq . > /dev/null 2>&1; then
            echo "Valid JSON Response"
          else
            echo "Invalid JSON Response"
            exit 1
          fi
