name: Update Data

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Updated to v3 to use Node.js 20

      - name: Fetch ELO Data and Update JSON
        run: |
          echo "[]" > elo_data.json
          for profileId in 8425727 262331 7104296 2259426; do
            elo1v1=$(curl -s "https://aoe2.net/api/player/ratinghistory?game=aoe2de&leaderboard_id=3&profile_id=$profileId&count=1" | jq -r '.[0].rating')
            eloTeam=$(curl -s "https://aoe2.net/api/player/ratinghistory?game=aoe2de&leaderboard_id=4&profile_id=$profileId&count=1" | jq -r '.[0].rating')
            jq --arg profileId "$profileId" --arg elo1v1 "$elo1v1" --arg eloTeam "$eloTeam" \
              '. += [{"profileId": $profileId, "elo1v1": $elo1v1, "eloTeam": $eloTeam}]' \
              elo_data.json > tmp.json && mv tmp.json elo_data.json
          done

      - name: Fetch Live Status and Update JSON
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_ACCESS_TOKEN: ${{ secrets.TWITCH_ACCESS_TOKEN }}
        run: |
          echo "[]" > live_status.json
          for streamer in inertiacreeping shiderplays ttambow chestnutplace77; do
            response=$(curl -s -H "Client-ID: $TWITCH_CLIENT_ID" -H "Authorization: Bearer $TWITCH_ACCESS_TOKEN" "https://api.twitch.tv/helix/streams?user_login=$streamer")
            is_live=$(echo $response | jq '.data | length > 0')
            jq --argjson is_live $is_live --arg name $streamer '. += [{"name": $name, "is_live": $is_live}]' live_status.json > tmp.json && mv tmp.json live_status.json
          done

      - name: Commit and Push JSON
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git add elo_data.json live_status.json
          git commit -m "Update ELO and live status data"
          git push origin HEAD:main
